# NumPy Practice Notebook

This notebook demonstrates basic NumPy operations including:
- Array creation
- Indexing and slicing
- Mathematical operations
- Reshaping
- Broadcasting
- Array manipulation
- Random number generation

In [1]:
import numpy as np

## Creating a 1D Array


In [16]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)


[10 20 30 40 50]


## Creating a 2D Array
# contains 2 rows and 3 columns

In [5]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## Creating a 3D Array
# contains 2 rows and 2 columns

In [6]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Dimensions
## dimension refer to as number of indexes used to acces an element 

In [17]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
## Array Shape
## shape refer to as rows and columns present in array
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 3)
(2, 2, 2)


In [ ]:
## Creating Arrays Using arange()
## arange() functions is used to create array 

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
## Array Indexing
## indexing is refer to as accessing elements using indexes from array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[3])

10
40


In [21]:
## Negative Indexing
## negative indexing start from end point of array i.e last element 

print(arr[-1])
print(arr[-2])

50
40


In [ ]:
## Array Slicing
## slicing refers to as using index i.e start and end index(end index is not included) to access part of array
print(arr[1:4])

[20 30 40]


In [ ]:
## 2D Array Indexing
## accessing elemnt from 1 row and second column
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix[1, 2])

6


In [ ]:
## operation on arrays
## Addition of Arrays
## add elemnts column wise
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [ ]:
## Subtraction of Arrays
## subtracts elements from b to a
print(a - b)

[-3 -3 -3]


In [37]:
## Multiplication of Arrays
print(a * b)

[ 4 10 18]


In [38]:
## Division of Arrays
print(a / b)

[0.25 0.4  0.5 ]


In [ ]:
## Sum of Array Elements
## adds elements of an array
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [40]:
## Mean of Array Elements
print(np.mean(arr))

3.0


In [ ]:
## Standard Deviation

print(np.std(arr))

1.4142135623730951


In [ ]:
## Reshaping Arrays
## reshaping is referred to as changing 1D array to another Dimensonal array like 2D and 3D
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
## Flattening Arrays
## flattening of arrays means to regain array in original shape 
flat = reshaped.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
## Broadcasting Example
## Adding a scalar value to every elemen i.e it adds 1 to every element of the array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix + 10)

[[11 12 13]
 [14 15 16]]


In [46]:
## Broadcasting is the process by which NumPy automatically expands smaller arrays to match the shape of larger arrays so that arithmetic operations can be performed element-wise.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [ ]:
## Broadcasting Between Arrays
## here array a is 2D array with shape (3,1) that is 3 rows and 1 column and b copies it for each row and add elemts from array a
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
## Array Concatenation
## concatenation of arrays can be defined as adding one array with other
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

combined = np.concatenate((a, b))
print(combined)

[1 2 3 4 5 6]


In [48]:
## Finding Maximum and Minimum Values
arr = np.array([15, 7, 22, 3, 18])

print(np.max(arr))
print(np.min(arr))

22
3


In [ ]:
## Generating Random Numbers
## np.random.randint prints any random number with syntax (low,high,size)
random_ints = np.random.randint(1, 100, 10)
print(random_ints)

[30 92 76 40  8 55 55 47 32 95]
